[project]
name = "nyc-street-design-adherence"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "geopandas>=1.1.1",
    "osmnx>=2.0.5",
    "pandas>=2.3.1",
    "shapely>=2.1.1",
]
